
export const busEvents = {
	USER_UPDATED: 'USER_UPDATE',
	LOGIN: 'LOGIN',
	LOGIN_RESPONSE: 'LOGIN_RESPONSE',
	SIGNUP: 'SIGNUP',
	SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',
	LOGOUT: 'LOGOUT',
	ACCOUNT_GET: 'ACCOUNT_GET',
	CHANGE_USER_TYPE: 'CHANGE_USER_TYPE',
	JOBS_UPDATED: 'JOBS_UPDATED',
	JOBS_GET: 'JOBS_GET',
	JOB_GET: 'JOB_GET',
	JOB_UPDATED: 'JOB_UPDATED',
	PROPOSALS_GET: 'PROPOSALS_GET',
	PROPOSALS_UPDATED: 'PROPOSALS_UPDATED',
	PROPOSAL_CREATE: 'PROPOSALS_CREATE',
	PROPOSAL_CREATE_RESPONSE: 'PROPOSALS_CREATE_RESPONSE',
	ON_PAGE_LOAD: 'ON_PAGE_LOAD',
	FREELANCER_GET: 'FREELANCER_GET',
	FREELANCER_UPDATED: 'FREELANCER_UPDATED',
	FREELANCERS_GET: 'FREELANCERS_GET',
	FREELANCERS_UPDATED: 'FREELANCERS_UPDATED',
};

export const CSRF_TOKEN_NAME = 'csrf-token';
